config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  devise_for :support_agents, :controllers => { :invitation => 'support_agents/invitations' }
  devise_for :customers, controllers: { sessions: 'customers/sessions' }
  devise_for :admins
  resources :support_agents
  resources :customers
  mount API::Root => '/'
  root to: 'cross#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :bookings
	has_many :customers, through: :bookings
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:number, :room_type, :specification, :charges, :status)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
	def options_for_room_type
		options_for_select([["Deluxe Rooms", "Deluxe Rooms"], ["Luxury Rooms", "Luxury Rooms"], ["Luxury Suites", "Luxury Suites"],
		 ["Presidential Suites", "Presidential Suites"]])
	end

	def options_for_spec
		options_for_select([["Queen Size Bed", "Queen Size Bed"],
		 ["Queen Size Bed and Pool Facing", "Queen Size Bed and Pool Facing"],
		 ["King Size Bed and Pool Facing", "King Size Bed and Pool Facing"],
		 ["King Size Bed, Pool Facing with a Gym", "King Size Bed, Pool Facing with a Gym"]])
	end

	def options_for_status
		options_for_select([["Available", "Available"],
		 ["Booked", "Booked"]])
	end
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :room_type %>
    <%= f.select(:room_type, options_for_room_type) %>
  </div>

  <div class="field">
    <%= f.label :specification %>
    <%= f.select(:specification, options_for_spec) %>
  </div>

  <div class="field">
    <%= f.label :charges %> (Per Night)
    <%= f.text_field :charges %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.select(:status, options_for_status) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h3>Hotel Rooms</h3>
<table id="room_table" border="2">
  <thead>
    <tr>
      <th>Number</th>
      <th>Room Type</th>
      <th>Specification</th>
      <th>Charges</th>
      <th>Status</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>
  <tbody>
    <% if @rooms.present? %>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= room.number %></td>
          <td><%= room.room_type %></td>
          <td><%= room.specification %></td>
          <td><%= room.charges %></td>
          <td><%= room.status %></td>
          <td><%= link_to 'Show', room, class: "btn btn-info btn-lg" %></td>
          <td><%= link_to 'Edit', edit_room_path(room), class: "btn btn-info btn-lg" %></td>
          <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-info btn-lg" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<br>
<% if admin_signed_in? %>
  <%= link_to 'New Room', new_room_path, class: "btn btn-info btn-lg" %>
<% end %>

<script type="text/javascript">
  $(document).ready( function () {
      $('#room_table').DataTable({
          "paging": true,
          "scrollY": 400,
          "ordering": true
        });
  } );
</script>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room Number:</strong>
  <%= @room.number %>
</p>

<p>
  <strong>Room Type:</strong>
  <%= @room.room_type %>
</p>

<p>
  <strong>Specification:</strong>
  <%= @room.specification %>
</p>

<p>
  <strong>Charges (Per Night):</strong>
  <%= @room.charges %>
</p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>