config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :rooms
  devise_for :support_agents, :controllers => { :invitation => 'support_agents/invitations' }
  devise_for :customers, controllers: { sessions: 'customers/sessions' }
  devise_for :admins
  resources :support_agents
  resources :customers
  mount API::Root => '/'
  root to: 'cross#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Hotel Room Bookings System</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
  		<script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
	</head>
	<style>
		body {
			background-color: lightblue;
		}
	</style>
	<body>
		<div class="container">
		<% if admin_signed_in? %>
		    <p>Welcome <%= current_admin.email %> </p>
			<%= link_to "Sign out", destroy_admin_session_path, class: "btn btn-info btn-lg", :method => :delete %>
			<%= link_to "Invite Support Agent", new_support_agent_invitation_path, class: "btn btn-info btn-lg" %>
		<% elsif customer_signed_in?  %>
		    <p id="notice">Welcome  <%= current_customer.email %>  </p>
			<%= link_to "Sign out", destroy_customer_session_path, class: "btn btn-info btn-lg", :method => :delete %>
		<% elsif support_agent_signed_in? %>
		    <p id="notice">Welcome <%= current_support_agent.email %>  </p>
			<%= link_to "Sign out", destroy_support_agent_session_path, class: "btn btn-info btn-lg", :method => :delete %>
		<% end %>
		<% if notice.present? %>
			<div class="alert alert-success"><%= notice %></div>
		<% end %>
		<% if alert.present? %>
			<div class="alert alert-warning"><%= alert %></div>
		<% end %>
		<%= yield %>
		</div>
	</body>
</html>